Bump the version to 0.3.dev0 because we intend to refactor the API yet again:
1. Remove class methods because of python's confusing instance
   collisions. Example with current API:

   .. code:: python

      >>> NEWT = dimana.Units.parse('NEWTON')
      >>> NEWT.parse('42')
      Traceback (most recent call last):
        ...
      ParseError: Could not parse Units: '42'

      >>> NEWT.from_string('42')
      <Value '42 [NEWTON]'>

   The purpose of `from_string` is to parse an amount and produce a
   NEWTON value for it. So `parse` would be a natural method name,
   yet this is a collision with the class method which parses a unit
   specification into a Units instance.

2. Overload construction/making to be pythonic.

   Right now constructors/makers are intended to be "strict" with higher
   level construction in explicitly named methods. I expect the vast
   majority of use needs the explicit method construction approaches,
   so it's burdensome. The explicitness can be encoded into varying
   parameters to a constructor/maker in the common pythonic way, instead.

   For example, here's a new desired API:

   .. code:: python

      >>> METER = dimana.Units('METER')
      >>> length = METER(42)
      >>> length / dimana.parse_value('7 [SEC]')
      <Value '6 [METER / SEC]'>

3. Add a "magic Units attr factory" with this kind of API:

   .. code:: python

      >>> from dimana import parse_units
      >>> from dimana import UnitsMaker as U
      >>> U.METER is parse_units('METER')
      True